### ISSUE TITLE
Florida shelters that are marked as whitelisted

### ISSUE THREAD

**Issue by simonw** [simonw/disaster-data#2]
If you see a shelter listed in https://github.com/simonw/irma-scraped-data/blob/master/florida-shelters-missing.json which is NOT actually missing from https://irma-api.herokuapp.com/shelters paste the details in here as a comment and the bot will know not to flag it as a potentially missing shelter.

**Comment by simonw** [comment]
University of Florida- Southwest Recreation Center (Alachua County)
  Type: General
  3150 Hull Road
  GAINESVILLE, FL 32611
  http://maps.google.com/maps?saddr=&daddr=29.63767190,-82.36276120

This one is here: https://irma-api.herokuapp.com/shelters/1106

**Comment by simonw** [comment]
Williams Elementary School (Alachua County)
  Type: General
  1245 SE 7th Ave
  GAINESVILLE, FL 32641
  http://maps.google.com/maps?saddr=&daddr=29.64561910,-82.30990870

https://irma-api.herokuapp.com/shelters/637

**Comment by iburn319** [comment]
Roulhac Ms Special Needs (Washington County)
  Type: Special Needs
  1535 Brckyard Rd
  CHIPLEY, FL 32428
  http://maps.google.com/maps?saddr=&daddr=30.76490550,-85.56796950

**Comment by simonw** [comment]
FIRST BAPTIST CHURCH (Starke) (Bradford County)
  Type: General
  163 W JEFFERSON ST
  STARKE, FL 32091
  http://maps.google.com/maps?saddr=&daddr=29.94496752,-82.11000169

https://irma-api.herokuapp.com/shelters/748

**Comment by simonw** [comment]
Bayside High School (Brevard County)
  Type: General
  1901 DEGROODT RD SW
  PALM BAY, FL 32908
  http://maps.google.com/maps?saddr=&daddr=27.94788200,-80.67492300

https://irma-api.herokuapp.com/shelters/195

**Comment by iburn319** [comment]
Suwannee Intermediate School (Suwannee County)
  Type: General
  1730 WALKER AVE SW
  LIVE OAK, FL 32064
  http://maps.google.com/maps?saddr=&daddr=30.27799410,-82.99624550

This address is for the elementary school (both elementary & intermediate schools are open shelters)

**Comment by simonw** [comment]
Space Coast Jr/sr High School (Brevard County)
  Type: General
  6150 Banyon St
  COCOA, FL 32927
  http://maps.google.com/maps?saddr=&daddr=28.47556840,-80.82619780

https://irma-api.herokuapp.com/shelters/737

**Comment by simonw** [comment]
Fox Trail Elementary School (Broward County)
  Type: General
  1250 S NOB HILL RD
  FORT LAUDERDALE, FL 33324
  http://maps.google.com/maps?saddr=&daddr=26.10409000,-80.27927690

https://irma-api.herokuapp.com/shelters/6

**Comment by iburn319** [comment]
Westgate K-8 (Saint Lucie County)
  Type: General
  1050 SW Cashmere Blvd
  PORT SAINT LUCIE, FL 34986
  http://maps.google.com/maps?saddr=&daddr=27.29502450,-80.38305850

Correct street is NW Cashmere

**Comment by simonw** [comment]
Indian Ridge Middle School Special Needs (Broward County)
  Type: Special Needs
  1355 Nob Hill Road
  FORT LAUDERDALE, FL 33324
  http://maps.google.com/maps?saddr=&daddr=26.10352100,-80.28395800

https://irma-api.herokuapp.com/shelters/1140

**Comment by iburn319** [comment]
Treasure Coast High School (Saint Lucie County)
  Type: General
  1000 SW Darwin Blvd
  PORT SAINT LUCIE, FL 34953
  http://maps.google.com/maps?saddr=&daddr=27.24463510,-80.36417280

**Comment by iburn319** [comment]
Oak Hammock K-8 (Saint Lucie County)
  Type: General
  1251 SW California Blvd
  PORT SAINT LUCIE, FL 34953
  http://maps.google.com/maps?saddr=&daddr=27.27794900,-80.38533590

**Comment by iburn319** [comment]
C A Moore Elementary School (Saint Lucie County)
  Type: General
  827 N 29Th St
  FORT PIERCE, FL 34947
  http://maps.google.com/maps?saddr=&daddr=27.45757590,-80.35410210

**Comment by iburn319** [comment]
MILL CREEK ELEMENTARY SCHOOL (Saint Johns County)
  Type: General
  3750 INTERNATIONAL GOLF
  SAINT AUGUSTINE, FL 32092
  http://maps.google.com/maps?saddr=&daddr=29.96509921,-81.48942153

**Comment by iburn319** [comment]
Tenoroc High School (Polk County)
  Type: General
  4905 Saddle Creek Road
  LAKELAND, FL 33801
  http://maps.google.com/maps?saddr=&daddr=28.07153500,-81.85805300

**Comment by simonw** [comment]
{
    "city": "W MELBOURNE, FL 32904", 
    "name": "Max Rodes Community Center - Special Needs", 
    "county": "Brevard", 
    "map_url": "http://maps.google.com/maps?saddr=&daddr=28.06105900,-80.68352800", 
    "geohash": "dhyxsh", 
    "address": "3410 W Flanagan Ave", 
    "type": "Special Needs"
  }, 

https://irma-api.herokuapp.com/shelters/1133

**Comment by iburn319** [comment]
Ridge Community High School (Polk County)
  Type: Special Needs
  500 Orchid Dr
  DAVENPORT, FL 33837
  http://maps.google.com/maps?saddr=&daddr=28.15306300,-81.62952700

**Comment by iburn319** [comment]
Lake Region High School (Polk County)
  Type: General
  1995 Thunder Rd
  EAGLE LAKE, FL 33839
  http://maps.google.com/maps?saddr=&daddr=27.98032200,-81.75007092

**Comment by iburn319** [comment]
Donald Bronson Community Center (Polk County)
  Type: General
  124 Bronson Trail
  POLK CITY, FL 33868
  http://maps.google.com/maps?saddr=&daddr=28.18344400,-81.82254500

**Comment by iburn319** [comment]
Oak Grove Middle School Special Needs (Pinellas County)
  Type: Special Needs
  1370 South Belcher Road
  CLEARWATER, FL 33764
  http://maps.google.com/maps?saddr=&daddr=27.94674900,-82.74815700

**Comment by iburn319** [comment]
OAK GROVE MIDDLE SCHOOL (Pinellas County)
  Type: Special Needs
  1370 S BELCHER RD
  CLEARWATER, FL 33764
  http://maps.google.com/maps?saddr=&daddr=27.94727320,-82.74797940

**Comment by iburn319** [comment]
Lealman Intermediate (Pinellas County)
  Type: General
  4900 28th St. N
  SAINT PETERSBURG, FL 33714
  http://maps.google.com/maps?saddr=&daddr=27.81646270,-82.67143140

First listed as "Lealman Innovation Academy"

**Comment by iburn319** [comment]
Joseph L Carwise Middle School (Pinellas County)
  Type: General
  3301 BENTLEY DR
  PALM HARBOR, FL 34684
  http://maps.google.com/maps?saddr=&daddr=28.08847100,-82.72733700

**Comment by iburn319** [comment]
JOHN M SEXTON ELEMENTARY SCHOOL (Pinellas County)
  Type: General
  1997 54TH AVE N
  SAINT PETERSBURG, FL 33714
  http://maps.google.com/maps?saddr=&daddr=27.82133070,-82.66044210

**Comment by iburn319** [comment]
Campbell Park Elementary (Pinellas County)
  Type: General
  1051 7th Ave. S
  SAINT PETERSBURG, FL 33705
  http://maps.google.com/maps?saddr=&daddr=27.76371200,-82.64956100

**Comment by iburn319** [comment]
RAYMOND B. STEWART MIDDLE SCHOOL (Pasco County)
  Type: General
  38505 10th Ave,
  ZEPHYRHILLS, FL 33542
  http://maps.google.com/maps?saddr=&daddr=28.24051719,-82.17823931

**Comment by iburn319** [comment]
ODESSA ELEMENTARY SCHOOL (Pasco County)
  Type: General
  12810 Interlaken Rd
  NEW PORT RICHEY, FL 34655
  http://maps.google.com/maps?saddr=&daddr=28.18538500,-82.60242200

**Comment by iburn319** [comment]
Apopka Memorial Middle School (Orange County)
  Type: General
  800 N. WELLS ST.
  APOPKA, FL 32712
  http://maps.google.com/maps?saddr=&daddr=28.69640800,-81.52051890

**Comment by iburn319** [comment]
Bryceville Elementary School (Nassau County)
  Type: General
  6504 Church Road
  CALLAHAN, FL 32011
  http://maps.google.com/maps?saddr=&daddr=30.38610500,-81.94039900

**Comment by iburn319** [comment]
South Dade HS (Miami-Dade County)
  Type: General
  28401 SW 187th Ave
  MIAMI, FL 33132
  http://maps.google.com/maps?saddr=&daddr=25.50258370,-80.49394860

Wrong street name.

**Comment by iburn319** [comment]
Linda Lentin K-8 Center (Miami-Dade County)
  Type: General
  14312 NE 2nd CT
  NORTH MIAMI, FL 33161
  http://maps.google.com/maps?saddr=&daddr=25.88938420,-80.19363120

**Comment by iburn319** [comment]
Jorge Mas Canosa Middle School (Miami-Dade County)
  Type: General
  500 SW 109 Avenue
  MIAMI, FL 33174
  http://maps.google.com/maps?saddr=&daddr=25.76399430,-80.37295380

Wrong Street

**Comment by iburn319** [comment]
Hialeah - Miami  Lakes Hign School (Miami-Dade County)
  Type: General
  7977 W 12TH AVE
  Hialeah, FL 33014
  http://maps.google.com/maps?saddr=&daddr=25.89408299,-80.30800903

**Comment by iburn319** [comment]
Hammocks Middle School (Miami-Dade County)
  Type: General
  9889 HAMMOCKS BLVD
  MIAMI, FL 33196
  http://maps.google.com/maps?saddr=&daddr=25.67421100,-80.44199700

**Comment by iburn319** [comment]
Florida International University (Miami-Dade County)
  Type: General
  11200 SOUTH WEST 8TH STREET
  MIAMI, FL 33165
  http://maps.google.com/maps?saddr=&daddr=25.75737400,-80.37620700

This address is for the school, the shelter (Rec Center) has a different address

**Comment by iburn319** [comment]
FIU COLLEGE OF BUSINESS COMPLEX (Miami-Dade County)
  Type: General
  11200 SW 8th Street
  FLORIDA INTERNATIONAL UNIV, FL 33199
  http://maps.google.com/maps?saddr=&daddr=25.75657600,-80.37394900

**Comment by iburn319** [comment]
NORTH MARION MIDDLE SCHOOL (Marion County)
  Type: General
  2085 NW HWY 329
  Citra, FL 32113
  http://maps.google.com/maps?saddr=&daddr=29.33249000,-82.16318300

**Comment by iburn319** [comment]
ROBERT H. PRINE ELEMENTARY (Manatee County)
  Type: General
  3801 SOUTHERN PKWY W
  BRADENTON, FL 34205
  http://maps.google.com/maps?saddr=&daddr=27.47199100,-82.59680800

**Comment by iburn319** [comment]
GILBERT W MCNEAL ELEMENTARY SCHOOL (Manatee County)
  Type: General
  6325 LORRAINE RD
  BRADENTON, FL 34202
  http://maps.google.com/maps?saddr=&daddr=27.42818742,-82.39534760

**Comment by iburn319** [comment]
WILLISTON MIDDLE SCHOOL (Levy County)
  Type: General
  20550 NE 42ND PL
  WILLISTON, FL 32696
  http://maps.google.com/maps?saddr=&daddr=29.39218469,-82.42821525

**Comment by iburn319** [comment]
Umatilla Elementary School Special Needs (Lake County)
  Type: Special Needs
  401 Lake Street
  UMATILLA, FL 32784
  http://maps.google.com/maps?saddr=&daddr=28.93806500,-81.67195900

**Comment by iburn319** [comment]
Leesburg High School (Lake County)
  Type: General
  1401 Yellow Jacket Way
  LEESBURG, FL 34748
  http://maps.google.com/maps?saddr=&daddr=28.80847200,-81.88876000

**Comment by iburn319** [comment]
Somerset Academy (formerly Jefferson County HS) (Jefferson County)
  Type: General
  50 David Road
  MONTICELLO, FL 32344
  http://maps.google.com/maps?saddr=&daddr=30.49057100,-83.88134300

**Comment by iburn319** [comment]
Bonifay Middle School (Holmes County)
  Type: General
  401 McLaughlin Ave
  BONIFAY, FL 32425
  http://maps.google.com/maps?saddr=&daddr=30.79457600,-85.68200000

**Comment by iburn319** [comment]
West Hernando Middle School (Hernando County)
  Type: General
  14325 Ken Austin Parkway
  BROOKSVILLE, FL 34614
  http://maps.google.com/maps?saddr=&daddr=28.56435700,-82.49051200

**Comment by iburn319** [comment]
Explorer K-8 (Hernando County)
  Type: General
  10252 Northcliffe Blvd
  SPRING HILL, FL 34608
  http://maps.google.com/maps?saddr=&daddr=28.49081000,-82.55349600

**Comment by iburn319** [comment]
Challenger K-8 (Hernando County)
  Type: Special Needs
  14325 Ken Austin pkwy
  BROOKSVILLE, FL 34614
  http://maps.google.com/maps?saddr=&daddr=28.56434400,-82.49050900

**Comment by iburn319** [comment]
West Glades School Bldg 300 - Special Needs (Glades County)
  Type: Special Needs
  2586 cR 731
  LABELLE, FL 33935
  http://maps.google.com/maps?saddr=&daddr=26.80632880,-81.44189080

**Comment by iburn319** [comment]
Bunnell Elementary School (Flagler County)
  Type: General
  800 E Howe St
  BUNNELL, FL 32110
  http://maps.google.com/maps?saddr=&daddr=29.47080189,-81.25583158

**Comment by iburn319** [comment]
Twin Lakes Elementary School (Duval County)
  Type: General
  8000 POINT MEADOWS DR
  JACKSONVILLE, FL 32256
  http://maps.google.com/maps?saddr=&daddr=30.22363000,-81.51609500

**Comment by iburn319** [comment]
Oceanway Elementary School (Duval County)
  Type: General
  12555 GILLESPIE AVE
  JACKSONVILLE, FL 32218
  http://maps.google.com/maps?saddr=&daddr=30.46094800,-81.62263900
